name: setting up environment

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - main
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]
    
env:
  REPO: https://github.com/royalturd/test
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main
       
       - name: cloning repo
         run: |
           mkdir bot
           git clone $REPO bot
       - name: compilation
         run: |
           sudo dockerd
           cd bot
           docker build . -t leech
       - name: running Docker
         run: |
           docker run leech
